# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options

class TestSmokeTest():
  def setup_method(self, method):
    opts = Options()
    opts.add_argument("--headless")    
    self.driver = webdriver.Firefox(options=opts)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adminPageTest(self):
    self.driver.set_window_size(1200, 800)
    self.driver.get("http://localhost:5500/teton/1.6/index.html/teton/1.6/admin.html")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "input[name=\'username\']")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\'username\']").send_keys("fake")
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\'password\']").send_keys("password")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".errorMessage")
    assert len(elements) > 0
  
  def test_directoryPageTest(self):
    self.driver.set_window_size(1200, 800)
    self.driver.get("http://localhost:5500/teton/1.6/index.html/teton/1.6/directory.html")
    self.driver.find_element(By.CSS_SELECTOR, "#directory-grid").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#directory-data p")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "#directory-list").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#directory-data p")
    assert len(elements) > 0
  
  def test_homePageTest(self):
    self.driver.set_window_size(1200, 800)
    self.driver.get("http://localhost:5500/teton/1.6/index.html/teton/1.6/index.html")
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".a-button")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".a-button").click()
    attribute = self.driver.find_element(By.CSS_SELECTOR, "body").get_attribute("data-url")
    self.vars["currentURL"] = attribute
  
  def test_nameandLogoTest(self):
    self.driver.set_window_size(1200, 800)
    self.driver.get("http://localhost:5500/teton/1.6/index.html/teton/1.6/index.html")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "div.header-logo img")
    assert len(elements) > 0
    assert self.driver.title == "Teton Idaho CoC"
  
  def test_joinPageTest(self):
    self.driver.set_window_size(1200, 800)
    self.driver.get("http://localhost:5500/teton/1.6/index.html/teton/1.6/join.html")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "input[name=\'fname\']")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\'fname\']").send_keys("John")
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\'lname\']").send_keys("Doe")
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\'bizname\']").send_keys("Example")
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\'biztitle\']").send_keys("Example")
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\'submit\']").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "input[name=\'email\']")
    assert len(elements) > 0
  
