# Generated by Selenium IDE - FIXED URLs
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options


BASE_URL = "http://localhost:5500/teton/1.6"


class TestSmokeTest():
    def setup_method(self, method):
        opts = Options()
        opts.add_argument("--headless")
        self.driver = webdriver.Firefox(options=opts)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    # -------------------------
    # ADMIN PAGE TEST
    # -------------------------
    def test_adminPageTest(self):
        self.driver.set_window_size(1200, 800)
        self.driver.get(f"{BASE_URL}/admin.html")

        # username field should exist
        elements = self.driver.find_elements(By.CSS_SELECTOR, "input[name='username']")
        assert len(elements) > 0

        self.driver.find_element(By.CSS_SELECTOR, "input[name='username']").send_keys("fake")
        self.driver.find_element(By.CSS_SELECTOR, "input[name='password']").send_keys("password")
        self.driver.find_element(By.CSS_SELECTOR, ".mysubmit").click()

        # error message should appear
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".errorMessage")
        assert len(elements) > 0

    # -------------------------
    # DIRECTORY PAGE TEST
    # -------------------------
    def test_directoryPageTest(self):
        self.driver.set_window_size(1200, 800)
        self.driver.get(f"{BASE_URL}/directory.html")

        # grid view button exists
        self.driver.find_element(By.CSS_SELECTOR, "#directory-grid").click()
        elements = self.driver.find_elements(By.CSS_SELECTOR, "#directory-data p")
        assert len(elements) > 0

        # list view button exists
        self.driver.find_element(By.CSS_SELECTOR, "#directory-list").click()
        elements = self.driver.find_elements(By.CSS_SELECTOR, "#directory-data p")
        assert len(elements) > 0

    # -------------------------
    # HOME PAGE TEST
    # -------------------------
    def test_homePageTest(self):
        self.driver.set_window_size(1200, 800)
        self.driver.get(f"{BASE_URL}/index.html")

        assert self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1")
        assert self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2")
        assert self.driver.find_elements(By.CSS_SELECTOR, ".a-button")

        # click button
        self.driver.find_element(By.CSS_SELECTOR, ".a-button").click()

    # -------------------------
    # LOGO + TITLE TEST
    # -------------------------
    def test_nameandLogoTest(self):
        self.driver.set_window_size(1200, 800)
        self.driver.get(f"{BASE_URL}/index.html")

        assert self.driver.find_elements(By.CSS_SELECTOR, "div.header-logo img")
        assert self.driver.title == "Teton Idaho CoC"

    # -------------------------
    # JOIN PAGE TEST
    # -------------------------
    def test_joinPageTest(self):
        self.driver.set_window_size(1200, 800)
        self.driver.get(f"{BASE_URL}/join.html")

        assert self.driver.find_elements(By.CSS_SELECTOR, "input[name='fname']")

        self.driver.find_element(By.CSS_SELECTOR, "input[name='fname']").send_keys("John")
        self.driver.find_element(By.CSS_SELECTOR, "input[name='lname']").send_keys("Doe")
        self.driver.find_element(By.CSS_SELECTOR, "input[name='bizname']").send_keys("Example")
        self.driver.find_element(By.CSS_SELECTOR, "input[name='biztitle']").send_keys("Example")
        self.driver.find_element(By.CSS_SELECTOR, "input[name='submit']").click()

        assert self.driver.find_elements(By.CSS_SELECTOR, "input[name='email']")

